### ISSUE TITLE
multitouch is weird

### ISSUE THREAD

**Issue by djdance** [bluedome/DragToReorderCollectionView#1]
the result of multitouch

![screen shot 2016-07-03 at 15 49 25](https://cloud.githubusercontent.com/assets/2269720/16545519/227e4e34-4136-11e6-99b7-68d14d04fd76.png)

**Comment by bluedome** [comment]
thanks for reporting.
i fixed the issue.

**Comment by djdance** [comment]
no, not work. Result is the same.
it drops previous cell #0 as an image on second finger touch, then starts to jump between 2 fingers, dragging real #0 and #1 , so #0 is duplicated

anyway, thanks for your work

**Comment by djdance** [comment]
the same if clear "Multiply touch" checkbox in storyboard in Collection View

upd. also tried **gesture.maximumNumberOfTouches=1**, not work

**Comment by djdance** [comment]
this works.

```
        if gestureRecognizer.state == .Began {
            if pannedIndexPath != nil {
                return
            }
```

**Comment by bluedome** [comment]
ok.
i fixed it again.
how about that?

**Comment by djdance** [comment]
works.
